name: Lint commit message

on:
  push:
    branches:
      - staging
      - staging-vue3
      - production
      - vue3

jobs:
  commit_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Lint commit message
        run: |
          echo "This commit should adhere to the commit message convention."
          echo "correct format: <type>(<scope>): <subject>"
          echo "example: feat: add modal component"
          echo "Please amend your commit message (git commit --amend) if commitlint reports an error and push using: git push --force-with-lease"
          npx commitlint --verbose << EOF
          ${{ github.event.head_commit.message }}
          EOF
